name: Unit tests

on:
    push:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    phpunit:
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[ci skip]')"

        strategy:
            matrix:
                include:
                    #-   os: ubuntu-18.04
                    #    php-version: '7.2'
                    -   os: ubuntu-latest
                        php-version: '7.4'

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: gd, intl, pdo_mysql
                    coverage: none # disable xdebug, pcov

            -   name: Composer install
                uses: ramsey/composer-install@v1
                with:
                    composer-options: '--ansi --prefer-dist'

            -   name: Setup Problem Matchers for PHPUnit
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: Run phpunit
                run: vendor/bin/phpunit --colors=always
